### ISSUE TITLE
Function "store_chain" crashes when parameters have the same name and index

### ISSUE THREAD

**Issue by alexkolo** [JohannesBuchner/BXA#10]
When using more than one data-group in XSPEC, which happens when you are fitting more than one spectrum, and using the same model for different data-groups, one will end up in having model parameters with the same name and model-index for different data-groups.
So far this isn't a problem. However, the BXA function "store_chain" creates a FITS-Table to be used for the XPSEC task `chain`, where it names each column with parameter name and its model-index:
`columns = [pyfits.Column(name='%s__%d' % (t['name'], t['index']), ` (Line 33 of `__init__.py`)
Hence, when letting the same parameter be free for more than one data-group (e.g. Instrumental Background Normalization), "pyfits"  will crash because it can't create a FITS-Table with identical columns. I guess, one simple workaround would be to create the column names beforehand and clean for identical names. I just removed this part from the BXA code, since I don't really know how to make use of those chain-FITS-Files.

**Comment by JohannesBuchner** [comment]
Yes, this is a good point. The code here is supposed to make columns compatible with xspec's mcmc functionality. I am not sure what xspec does in case of similar names. Does it attach the data group id or parameter id?

**Comment by alexkolo** [comment]
I neither know what XSPEC does for such cases, since I never used xspec's mcmc functionality.
As for BXA, one can get from `xc.AllData.nGroups` the total number of Data-Groups, which could be used to trigger a user warning if it's larger than one. However, BXA doesn't know from the `transformations` variable itself which parameter belongs to which Data-Group. Maybe, one could create an additional input variable for BXA, which supplies this information and which becomes mandatory if parameters from more than one data-group are used.

**Comment by ferrigno** [comment]
The following code snippet can be easily used to overcome this issue
`group_index=1
old_model=transformations[0]['model']
for t in transformations:
    if t['model'] != old_model:
        group_index+=1
        old_model=t['model']
    print(t['name'], t['index']+(group_index-1)*old_model.nParameters)`

**Comment by JohannesBuchner** [comment]
Thanks @ferrigno, I added your suggestion in the branch feature-multidatachain . Could you (or @alexkolo ) check out that branch and test if the fits files work in xspec?

**Comment by ferrigno** [comment]
Hi @JohannesBuchner . I have tested it in one case and it works. Thanks a lot for your prompt reaction.

**Comment by ferrigno** [comment]
Hi. I used it again and it works. Feele free to merge it on the master branch, if you wish.

**Comment by JohannesBuchner** [comment]
done.
