### ISSUE TITLE
Document Ultranest interface BXASolver

### ISSUE THREAD

**Issue by alexkolo** [JohannesBuchner/BXA#11]
Since `Ultranest` is online now, will the next update of `BXA` also using it instead of `Multinest`?
Under the hood both packages are doing the same, I assume (or are there some performance improvements as well?).
However, with `Ultranest` the installation of `BXA` should be much easier, right?

PS: nice package naming ;)

**Comment by JohannesBuchner** [comment]
Yes, it is in fact already available, through the bxa.xspec.solver and bxa.sherpa.solver API. You can prevent loading of the multinest library by setting the environment variable WITHOUT_MULTINEST to 1. There are still some minor differences to be understood, and you can help with testing.

**Comment by alexkolo** [comment]
Great. I'm not using it at the moment but a collaborator will start using it rather soon.

**Comment by JohannesBuchner** [comment]
New documentation is available at https://johannesbuchner.github.io/BXA/
