### ISSUE TITLE
Chain can be loaded in Xspec but not used for error estimate

### ISSUE THREAD

**Issue by ferrigno** [JohannesBuchner/BXA#12]
If I load the chain built with bxa into xspec, it is not used to compute the errors or the flux uncertainties.
I tried with the chain produced by xspec and it works as expected.

It must be something in the format that makes the difference, but finding exactly what is challenging.

**Comment by JohannesBuchner** [comment]
Hi @ferrigno, sorry for not responding yet. Did you find a solution?

**Comment by ferrigno** [comment]
Hi @JohannesBuchner . No problems, you were busy wit ultranest  :). The issue is that you save the parameters in the chain with a different convention from xspec, so they cannot be loaded directly into Xspec (I do not remember the details of underscores, dash, numbers, now). I loaded the chain into python using pandas and I managed to compute errors. However, it would be more handy if you save parameters in the chain using the same convention of xspec. It should be easy, just make a GW chain into xspec with a model phabs*powerlaw+phabs*gaus+gaus. Then do the same with and with BXA and make sure the chains have the same names of parameters (the weird model is to account for multiple components and parameters with the same name).

**Comment by JohannesBuchner** [comment]
That's the intent ... apparently there is a bug in naming of the columns. Hopefully someone runs into the issue and proposes a solution.

Computing errors should be easy, you can get the chains also right from the BXASolver object.
