### ISSUE TITLE
file name autobackgroundmodel/__init__.py

### ISSUE THREAD

**Issue by lewtonstein** [JohannesBuchner/BXA#16]
Could you add "_{ndata}" to the name of the output file in autobackgroundmodel/__init__.py, since it is required by autobackgroundmodel/fitbkg.py?

**Comment by JohannesBuchner** [comment]
Does commit a20c8dca93d692bf61429d7ce40b861ddae42a24 fix this for you? For a file ready to be used for the entire telescope, you will need to rename the file to remove the instrument name (or _MERGED, in case of multiple instruments).
