### ISSUE TITLE
an error in gof.py

### ISSUE THREAD

**Issue by ellot** [JohannesBuchner/BXA#18]
I use BXA in pyxspec. In some cases, there are nan values in lowmodel_parts.  So the assert error is reported in line 85 of gof.py. 
I find some values of kplusones equal 0 (line 78, 79).

**Comment by JohannesBuchner** [comment]
Hmm, doesn't that mean data was <0 somewhere? Are you using binning on non-count data somehow?

**Comment by ellot** [comment]
Yes, in few cases, the net counts (subtracting background) is <0.

**Comment by JohannesBuchner** [comment]
That code (binning function) is only supposed to be run on count data, not subtracted data.

**Comment by JohannesBuchner** [comment]
Probably the exception should be raised earlier, in the binning function.

**Comment by JohannesBuchner** [comment]
Please reopen this if you still have the issue, and provide a code example with data.
