### ISSUE TITLE
JOSS review: examples/tests

### ISSUE THREAD

**Issue by cescalara** [JohannesBuchner/BXA#20]
Hi, some more comments on the example code:

- [x] It seems that some of the sherpa examples rely on `npyinterp` and python 2? Could this be updated to python 3? Please correct me if I am wrong. 
- [x] The example code in `docker/` also seems a bit outdated (e.g. doesn't use `ultranest` and python 3). OK if you want to keep this for reference, but then an up-to-date docker example should be added too.
- [x] What is the difference between `xagnfitter.py` detailed in the docs and `fitagn.py` in the docker examples?
- [x] When running `gal.py` I get a connection timeout to swift.ac.uk (looks likely to be a temporary problem on their side, so just to notify you)
- [x] Can you fix the latest Travis CI build? Seems that the examples run fine and it should work

**Comment by cescalara** [comment]
Linking [openjournals/joss-reviews/issues/3045](https://github.com/openjournals/joss-reviews/issues/3045)

**Comment by JohannesBuchner** [comment]
> Hi, some more comments on the example code:
> 
>     * It seems that some of the sherpa examples rely on `npyinterp` and python 2? Could this be updated to python 3? Please correct me if I am wrong.

I think it should run with python3 (I just also fixed the test.py there). Can you send me an error message?

>     * The example code in `docker/` also seems a bit outdated (e.g. doesn't use `ultranest` and python 3). OK if you want to keep this for reference, but then an up-to-date docker example should be added too.
>     * What is the difference between `xagnfitter.py` detailed in the docs and `fitagn.py` in the docker examples?

The docker stuff is outdated. It is not mentioned in the paper and in the doc. It is only there in case someone wants to revive it.

Is it possible to not evaluate it, or do I have to delete it?

>     * When running `gal.py` I get a connection timeout to swift.ac.uk (looks likely to be a temporary problem on their side, so just to notify you)
> 
>     * Can you fix the latest Travis CI build? Seems that the examples run fine and it should work

Yes, I think this is a small syntax issue in the CI code. Working on it.

**Comment by JohannesBuchner** [comment]
Build is green https://travis-ci.com/github/JohannesBuchner/BXA/builds/219436753

**Comment by cescalara** [comment]
Hi, 

> I think it should run with python3 (I just also fixed the test.py there). Can you send me an error message?

Yes you're right, it runs fine. For me, the Makefile doesn't work out of the box and I had to use `np.get_include()` to grab the numpy headers path. Maybe you could include this in the Makefile or use a setup.py. 

> The docker stuff is outdated. It is not mentioned in the paper and in the doc. It is only there in case someone wants to revive it.

OK, I understand, no need to delete it. I just got confused when wandering around the repo looking for examples as it is part of your CI tests. I was thinking it could be nice to have an up-to-date docker ready for users, given how it can be painful to install Xspec/Sherpa. However on second thoughts this would probably be a nightmare to maintain, so up to you if you want to add anything new.

**Comment by cescalara** [comment]
When checking the sherpa examples again I noticed that you need to `import os` in `example_pcabackground.py`. I guess this is a python 2/3 thing.

**Comment by JohannesBuchner** [comment]
> Yes you're right, it runs fine. For me, the Makefile doesn't work out of the box and I had to use `np.get_include()` to grab the numpy headers path. Maybe you could include this in the Makefile or use a setup.py.

Ideally, this would become a cython package with proper setup.py, but at the time I did not know how to do this. It is legacy code which only few people will need, which hopefully (like you) can adapt the Makefile if it doesn't work, and otherwise raise issues or email me.

> However on second thoughts this would probably be a nightmare to maintain, 

Additionally, there are also licensing issues ... alas not all of it is FOSS.

> When checking the sherpa examples again I noticed that you need to import os, numpy in example_pcabackground.py. I guess this is a python 2/3 thing.

The script was written for "sherpa", which is a command launching an ipython environment with some modules preloaded. I added an import (6dd578cae), which hopefully enables use with the python3 command as well.

I hope this addresses the issues.

**Comment by cescalara** [comment]
Ahh I see. Yup looks good.
