### ISSUE TITLE
JOSS Review: XSPEC Examples output

### ISSUE THREAD

**Issue by grburgess** [JohannesBuchner/BXA#23]
The gen.xspec script functions properly and the examples all run correctly. 

It would be nice if the large amount of output from the sampler was removed from the docs / README as it is difficult to find the relevant information without a lot of scrolling. Is the output needed for any purpose?

**Comment by grburgess** [comment]
linking https://github.com/openjournals/joss-reviews/issues/3045

**Comment by JohannesBuchner** [comment]
I thought it would be instructive to see the output and the progress evolution while scrolling through.
