### ISSUE TITLE
JOSS review: Background model examples

### ISSUE THREAD

**Issue by grburgess** [JohannesBuchner/BXA#26]
Currently the background model examples depend on both Sherpa and XSPEC. 

Is there a way to separate these into analysis framework independent examples or is the functionality tied to having both frameworks installed?

**Comment by grburgess** [comment]
linking openjournals/joss-reviews#3045

**Comment by JohannesBuchner** [comment]
The functionality is tied to having one of the two frameworks installed. Closing (the review was completed).
