### ISSUE TITLE
[Feature request] An option to save the model

### ISSUE THREAD

**Issue by DevangLiya** [JohannesBuchner/BXA#33]
Hi,

Is there an option to save the model file similar to the one in Xspec? It becomes difficult to track the exact models/configurations while doing many fits. I currently solve this issue by simply adding ```Xset.save(filename, 'm')``` to the programs, but it would be good to have that option within BXA if possible.

Thanks!

**Comment by DevangLiya** [comment]
Saving the model formula, parameter ranges and linked parameters would be helpful. In addition to that, saving the data (along with the noticed channels) and the prior information would be amazing if it's not too much work.

**Comment by JohannesBuchner** [comment]
yes, you have to look whether you are rank 0.

https://github.com/JohannesBuchner/UltraNest/blob/master/ultranest/integrator.py#L489-L501 

Regarding interactivity/overwriting, you'd have to consult the pyxspec manual. I think there is an option.

**Comment by DevangLiya** [comment]
I see. Thanks for the help!
