### ISSUE TITLE
Astropy 3.x compatability

### ISSUE THREAD

**Issue by bwgref** [JohannesBuchner/BXA#4]
Hi Johannes,

Just checking to see if there's a plan to make BXA work with the latest Astropy. It looks like things are getting wonky due to a change to the astropy.fits.io API.

Thanks,

-Brian

**Comment by JohannesBuchner** [comment]
Hi, could you please test with the feature-auto branch? I mean to release that one.

**Comment by bwgref** [comment]
Hi Johannes,

I’ll do that in a minute. It turns out there’s only two lines in xspec/__init.py__ that are really affect by the change in the astropy API. But I’ll take a look at that branch and let you know.

Cheers,

-BG



Brian Grefenstette
Research Scientist
Space Radiation Lab
California Institute of Technology
Pasadena, CA 91125
bwgref@srl.caltech.edu<mailto:bwgref@srl.caltech.edu>
(626) 395-8037

On Oct 3, 2018, at 4:55 PM, Johannes Buchner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, could you please test with the feature-auto branch? I mean to release that one.

**Comment by JohannesBuchner** [comment]
Hmm, actually I think I merged that into master already. If you can track down the problem I would really appreciate it. Ideally we can find a backwards-compatible solution.

**Comment by bwgref** [comment]
It's these two lines: 

        tbhdu = pyfits.new_table(table, header = header)
        tbhdu.update_ext_name('CHAIN')

Evidently astropy.io.fits depricated some old pyfits syntax somewhere along the way and finally got around to removing them from the API.

You can set the EXTNAME directly in the header and there's a new table generation API.

I went ahead and issued a PR, or you can grab it from my fork if you want to do any testing.

**Comment by bwgref** [comment]
Actually, you may want to grab it and do it yourself because I did a sloppy job of squashing those commits...

**Comment by JohannesBuchner** [comment]
Funny, I made the same changes already locally last week but didn't commit them. Can you test head?

**Comment by bwgref** [comment]
Still need to comment out or remove line 45:

        tbhdu.update_ext_name('CHAIN')
