### ISSUE TITLE
Simple workaround for character limit of "outputfiles_basename"

### ISSUE THREAD

**Issue by alexkolo** [JohannesBuchner/BXA#9]
I just wanted make users aware that the code crashes if the string `outputfiles_basename` is too long. I think it can't be more than 100 characters.
As a **workaround**, one can create all the files at a temporary short path and move them afterwards to the desired path, for instance with `shutil.move(Current, Target)`.
Note, that some BXA functions will try to access files at the temporary short path. Hence, one should complete the BXA analysis before moving/archiving the files.

**Comment by JohannesBuchner** [comment]
Ah, good point. Maybe an exception should be raised. The limit is indeed 100 characters (in MultiNest).

**Comment by JohannesBuchner** [comment]
Solved by latest release, which uses UltraNest.
